### ISSUE TITLE
"Show This" Webapp.

### ISSUE THREAD

**Issue by gleachkr** [gleachkr/Carnap-Old#31]
It'd be nice to have a webapp that just allows you to enter a sequent and then attempt to prove that sequent---this would work well with #30

**Comment by davidfaraci** [comment]
If possible, please include predicate rules; it would be nice to have a space to play with those (other than the main page).

**Comment by gleachkr** [comment]
:+1:

**Comment by gleachkr** [comment]
Ok, I think it's ready. There's a link on the front page, or you can get to it by following [this link](http://gleachkr.github.io/Carnap/Frontend/Ghcjs/Implementations/ShowThis/dist/build/ShowThis/ShowThis.jsexe/index.html)

**Comment by davidfaraci** [comment]
Awesome! I'll try to do some play-testing with predicates soon. A couple of issues for the moment:
1. I wouldn't populate the first line with Show:, since (a) people will probably start with their premises and (b) not all proofs will require a subproof. If it's possible, I would instead populate the first n lines with the premises.
2. Checks and Xs appear only when there are incomplete lines.
2. Currently, there is no indicator when you are actually finished, other than the fact that you've reached your conclusion and there are no error messages.

**Comment by gleachkr** [comment]
Great! I think items 1 and 2 should be easy to fix. W.r.t 3, The "goal" sequent should turn green when the proof is completed... Could you send a screenshot so I can try to reproduce the problem?

**Comment by davidfaraci** [comment]
I'll try. Of course now it's working...

**Comment by gleachkr** [comment]
Ok, I think 1 and 2 are now fixed.

**Comment by davidfaraci** [comment]
Awesome!
